app:
  feignclient:
    order-management-url: http://localhost:8080
stubrunner:
  username: admin
  password: admin
  ids:
    - com.mflyyou:order-management-service:+:stubs:8080
  repositoryRoot: http://localhost:9908/repository/maven-public/
  stubsMode: REMOTE